version: "2.7"

rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php worker.php"
  env:
    var_dumper_format: "server"
    var_dumper_server: "127.0.0.1:9912"

temporal:
  address: "127.0.0.1:7233"
  activities:
    num_workers: 4

logs:
  level: info
  mode: development
