<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: service.proto

namespace Test\CustomImport;

use Spiral\RoadRunner\GRPC;

interface ServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "import.Service";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param Message $in
    * @return Message
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function SimpleMethod(GRPC\ContextInterface $ctx, Message $in): Message;

    /**
    * @param GRPC\ContextInterface $ctx
    * @param \Test\CustomImport\Message\Message $in
    * @return \Test\CustomImport\Message\Message
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function ImportMethod(GRPC\ContextInterface $ctx, \Test\CustomImport\Message\Message $in): \Test\CustomImport\Message\Message;
}
