version: "3"

services:
  memcached:
    image: memcached:latest
    ports:
      - "127.0.0.1:11211:11211"

  redis:
    image: redis:6
    ports:
      - "127.0.0.1:6379:6379"

  redis2:
    image: redis:6
    ports:
      - "127.0.0.1:6378:6379"