version: "3"

services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"

  statsd:
    image: statsd/statsd
    ports:
      - "8125:8125/udp"
      - "8126:8126"

  postgresql:
    container_name: temporal-postgresql
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
    ports:
      - "5432:5432"

  temporal-ui:
    container_name: temporal-ui
    image: temporalio/ui:latest
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    ports:
      - "8080:8080"

  temporal:
    container_name: temporal
    image: temporalio/auto-setup:1
    depends_on:
      - postgresql
    environment:
      - LOG_LEVEL=debug
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgresql
    ports:
      - "7233:7233"

  temporal-admin-tools:
    container_name: temporal-admin-tools
    image: temporalio/admin-tools:1
    depends_on:
      - temporal
    environment:
      - TEMPORAL_CLI_ADDRESS=temporal:7233
      - LOG_LEVEL=debug
    stdin_open: true
    tty: true